### ISSUE TITLE
{Get Cards by partial name} response time is very high

### ISSUE THREAD

**Issue by AlessandroVerrecchia** [MagicTheGathering/mtg-sdk-kotlin#4]
`  val cardsResponse: Response<List<MtgCard>> = MtgCardApiClient.getCardsByPartialName(name, pageSize, page)
       
 val cards = cardsResponse.body()`

often takes a lot of time and can crash the app. 
i am pretty sure that i am not making the call in the best possible way (in an asynctask)

**Comment by asantalla** [comment]
Hi,

Sorry for the late late response. Sometimes the server has a big latency. So you should deal with the timeout in your app.

Regards
